{'json_eep/*', [debug_info, 
                {i, "./include"},
                {outdir, "./ebin"}]}.
{'src/*', [debug_info, 
          {i, "./json_eep"},
          {i, "./include"}, 
          {outdir, "./ebin"}]}.
