/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.swiftp;

public final class R {
    public static final class attr {
    }
    public static final class color {
        /**  Retrieved via Resources.getColor() and friends. 
         */
        public static final int red=0x7f040000;
    }
    public static final class drawable {
        /**  Retrieved via Resources.getDrawable() and friends. 
         */
        public static final int semi_black=0x7f020001;
        public static final int violet=0x7f020000;
    }
    public static final class id {
        public static final int add_user_button=0x7f070004;
        public static final int byline=0x7f070002;
        public static final int manage_users_button=0x7f070005;
        public static final int menu_top_text=0x7f070000;
        public static final int menu_url=0x7f070001;
        public static final int server_options_button=0x7f070006;
        public static final int start_stop_button=0x7f070003;
    }
    public static final class layout {
        public static final int server_control_activity=0x7f030000;
    }
    public static final class string {
        public static final int add_user=0x7f050004;
        /**  Simple strings. 
         */
        public static final int back=0x7f050000;
        public static final int clear=0x7f050001;
        public static final int manage_users=0x7f050005;
        public static final int menu_byline=0x7f050003;
        /**  This is a complex string containing style runs. 
         */
        public static final int menu_top_string=0x7f050002;
        public static final int menu_url=0x7f050008;
        public static final int server_options=0x7f050007;
        public static final int start_server=0x7f05000a;
        public static final int stop_server=0x7f050009;
        public static final int swiftp_name=0x7f050006;
    }
    public static final class style {
        public static final int ActionButton=0x7f060000;
        public static final int TextAppearance=0x7f060001;
        public static final int TextAppearance_ActionButton=0x7f060002;
    }
}
